# SPDX-FileCopyrightText: © 2022 Dai Foundation <www.daifoundation.org>
#
# SPDX-License-Identifier: Apache-2.0

from django.urls import path

from .views.assets import (
    AssetCEXTradingActivityPerAssetView,
    AssetCEXTradingActivityPerExchangeView,
    AssetCEXTradingActivityView,
    AssetCollateralView,
    AssetDailyVolatilityView,
    AssetDebtView,
    AssetDEXTradingActivityLiquidityView,
    AssetDEXTradingActivityVolumeView,
    AssetLiquidityScoreView,
    AssetOSMDrawdownsCountView,
    AssetPriceDrawdownsView,
    AssetPricesView,
    AssetsCEXVolumeView,
    AssetsDEXLiquidityView,
    AssetsDEXVolumeView,
    AssetsDrawdownsView,
    AssetSlippageHistoryView,
    AssetSlippageView,
    AssetsSlippagesView,
    AssetsView,
    AssetsVolatilityView,
)
from .views.auctions import (
    AuctionKickSimPerDayOSMView,
    AuctionKickSimPerDayView,
    AuctionKickSimPerParamOSMView,
    AuctionKickSimPerParamView,
)
from .views.d3m import (
    D3MComputeView,
    D3MDaiBorrowCurveView,
    D3MHistoricRatesView,
    D3MsView,
    D3MView,
)
from .views.dai_growth import DaiGrowth
from .views.dai_trades import (
    DAITradesDailyView,
    DAITradesLastDayView,
    DAITradesLastHoursView,
    DAITradesStatsView,
    DAITradesVolumePerExchangeView,
    DAITradesVolumeView,
)
from .views.defi import DEFILockedView, ETHMarketShareView, RatesView
from .views.forum import ForumArchiveView
from .views.ilk import (
    IlkCapitalAtRiskChartView,
    IlkCapitalAtRiskView,
    IlkEventStatsView,
    IlkHistoricStatsView,
    IlkLiquidationCurveView,
    IlkOSMView,
    IlkRiskPremiumModelChartView,
    IlkStatsView,
    IlksView,
    IlkView,
)
from .views.liquidations import (
    ActionsPerIlkPerDateView,
    AuctionsThroughputView,
    AuctionTakersKeepersView,
    AuctionThroughputView,
    KeepersView,
    LiquidationCurveView,
    LiquidationsAssetView,
    LiquidationsPerDateIlksView,
    LiquidationsPerDateIlkView,
    LiquidationsPerDateView,
    LiquidationsPerIlksView,
    LiquidationsPerIlkView,
    LiquidationsPeriodView,
    LiquidationsView,
    LiquidationView,
    SimulatedLiquidationsPerDropTableView,
    SimulatedLiquidationsPerDropView,
    TakersView,
)
from .views.osm import OracleHistoricStatsView, OSMAsset, OSMTableView
from .views.psm import (
    PSMDAISupplyHistoryView,
    PSMEventStatsView,
    PSMEventsView,
    PSMsDAISupplyHistoryView,
    PSMsEventStatsView,
    PSMsView,
)
from .views.risk import CapitalAtRiskOverallIlkView, CapitalAtRiskOverallView, GasView
from .views.risk import LiquidationCurveView as RiskLiquidationCurveView
from .views.risk import MakerStatsView, PercentOfRiskyDebtView
from .views.simulations import DustSimulationView, RiskModel, VaultsAtRiskSimulationView
from .views.vaults import (
    AllVaultPositionsView,
    VaultCrHistoryView,
    VaultDebtHistoryView,
    VaultEventsView,
    VaultPositionsView,
    VaultProtectionScoreMatrix,
    VaultsProtectionScoreHistoryView,
    VaultView,
)
from .views.vaults_at_risk import (
    VaultsAtRiskCountView,
    VaultsAtRiskMarketView,
    VaultsAtRiskView,
)
from .views.wallets import WalletDebtHistoryView, WalletEventsView, WalletView
from .views.whales import WhalesView

app_name = "maker"

urlpatterns = [
    path(
        "ilks/",
        IlksView.as_view(),
        name="ilks",
    ),
    path(
        "ilks/<str:ilk>/",
        IlkView.as_view(),
        name="ilk",
    ),
    path(
        "ilks/<str:ilk>/stats/",
        IlkStatsView.as_view(),
        name="ilk-stats",
    ),
    path(
        "ilks/<str:ilk>/stats/history/",
        IlkHistoricStatsView.as_view(),
        name="ilk-stats-history",
    ),
    path(
        "ilks/<str:ilk>/osm/",
        IlkOSMView.as_view(),
        name="ilk-osm",
    ),
    path(
        "ilks/<str:ilk>/liquidation-curve/",
        IlkLiquidationCurveView.as_view(),
        name="ilk-liquidation-curve",
    ),
    path(
        "ilks/<str:ilk>/vaults/",
        VaultPositionsView.as_view(),
        name="vaults-positions",
    ),
    path(
        "ilks/<str:ilk>/vaults/<str:uid>/",
        VaultView.as_view(),
        name="vault-view",
    ),
    path(
        "ilks/<str:ilk>/vaults/<str:uid>/protection-matrix/",
        VaultProtectionScoreMatrix.as_view(),
        name="vault-protection-matrix",
    ),
    path(
        "ilks/<str:ilk>/vaults/<str:uid>/events/",
        VaultEventsView.as_view(),
        name="vault-events",
    ),
    path(
        "ilks/<str:ilk>/vaults/<str:uid>/cr/",
        VaultCrHistoryView.as_view(),
        name="vault-cr",
    ),
    path(
        "ilks/<str:ilk>/vaults/<str:uid>/debt-history/",
        VaultDebtHistoryView.as_view(),
        name="vault-cr",
    ),
    path(
        "ilks/<str:ilk>/capital-at-risk/",
        IlkCapitalAtRiskView.as_view(),
        name="ilk-capital-at-risk",
    ),
    path(
        "ilks/<str:ilk>/capital-at-risk/chart/",
        IlkCapitalAtRiskChartView.as_view(),
        name="ilk-capital-at-risk-chart",
    ),
    path(
        "ilks/<str:ilk>/risk-premium/model/",
        IlkRiskPremiumModelChartView.as_view(),
        name="ilk-risk-premium-model",
    ),
    path(
        "ilks/<str:ilk>/event-stats/",
        IlkEventStatsView.as_view(),
        name="ilk-event-stats",
    ),
    path(
        "vaults/all/",
        AllVaultPositionsView.as_view(),
        name="vaults-all",
    ),
    path(
        "vaults-at-risk/",
        VaultsAtRiskView.as_view(),
        name="vaults-at-risk",
    ),
    path(
        "vaults-at-risk-market/",
        VaultsAtRiskMarketView.as_view(),
        name="vaults-at-risk-market",
    ),
    path(
        "vaults-at-risk/count/",
        VaultsAtRiskCountView.as_view(),
        name="vaults-at-risk-count",
    ),
    path(
        "liquidations/keepers-takers/",
        AuctionTakersKeepersView.as_view(),
        name="liquidation-keepers-takers",
    ),
    path(
        "liquidations/actions/",
        ActionsPerIlkPerDateView.as_view(),
        name="liquidation-actions",
    ),
    path(
        "liquidations/keepers/",
        KeepersView.as_view(),
        name="liquidations-keepers",
    ),
    path(
        "liquidations/takers/",
        TakersView.as_view(),
        name="liquidations-takers",
    ),
    path(
        "liquidations/table/",
        LiquidationsView.as_view(),
        name="liquidations-table",
    ),
    path(
        "liquidations/per-date/<str:date>/",
        LiquidationsPerDateIlksView.as_view(),
        name="liquidations-per-date-ilks",
    ),
    path(
        "liquidations/per-date/<str:date>/<str:ilk>/",
        LiquidationsPerDateIlkView.as_view(),
        name="liquidations-per-date-ilk",
    ),
    path(
        "liquidations/per-date/",
        LiquidationsPerDateView.as_view(),
        name="liquidations-per-date",
    ),
    path(
        "liquidations/assets/",
        LiquidationsAssetView.as_view(),
        name="liquidations-assets",
    ),
    path(
        "liquidations/per-ilks/",
        LiquidationsPerIlksView.as_view(),
        name="liquidations-per-ilks",
    ),
    path(
        "liquidations/per-ilks/<str:ilk>/",
        LiquidationsPerIlkView.as_view(),
        name="liquidations-per-ilks",
    ),
    path(
        "liquidations/<str:ilk>/",
        LiquidationsPerIlkView.as_view(),
        name="liquidations-per-ilk",
    ),
    path(
        "liquidations/<str:ilk>/<int:uid>/",
        LiquidationView.as_view(),
        name="liquidation-auction",
    ),
    path(
        "liquidations/",
        LiquidationsPeriodView.as_view(),
        name="liquidations",
    ),
    path(
        "liquidation-curve/",
        LiquidationCurveView.as_view(),
        name="liquidation-curve",
    ),
    path(
        "d3ms/",
        D3MsView.as_view(),
        name="d3ms",
    ),
    path(
        "d3ms/<str:protocol>/",
        D3MView.as_view(),
        name="d3m-protocol",
    ),
    path(
        "d3ms/<str:protocol>/simulation/",
        D3MComputeView.as_view(),
        name="d3m-protocol-compute",
    ),
    path(
        "d3ms/<str:protocol>/rates/",
        D3MHistoricRatesView.as_view(),
        name="d3m-protocol-rates",
    ),
    path(
        "d3ms/<str:protocol>/dai-borrow-curve/",
        D3MDaiBorrowCurveView.as_view(),
        name="d3m-protocol-dai-borrow-curve",
    ),
    path(
        "osm/",
        OSMTableView.as_view(),
        name="osm",
    ),
    path(
        "osm/<str:symbol>/",
        OracleHistoricStatsView.as_view(),
        name="osm-history",
    ),
    path(
        "auctions/throughput/",
        AuctionsThroughputView.as_view(),
        name="auctions-throughput",
    ),
    path(
        "auctions/throughput/<str:ilk>/",
        AuctionThroughputView.as_view(),
        name="auction-throughput",
    ),
    path(
        "auctions/kick-sim/per-day/<str:symbol>/",
        AuctionKickSimPerDayView.as_view(),
        name="auction-kick-sim-per-day",
    ),
    path(
        "auctions/kick-sim/per-day-osm/<str:symbol>/",
        AuctionKickSimPerDayOSMView.as_view(),
        name="auction-kick-sim-per-day",
    ),
    path(
        "auctions/kick-sim/per-param/<str:symbol>/",
        AuctionKickSimPerParamView.as_view(),
        name="auction-kick-sim-per-param",
    ),
    path(
        "auctions/kick-sim/per-param-osm/<str:symbol>/",
        AuctionKickSimPerParamOSMView.as_view(),
        name="auction-kick-sim-per-param",
    ),
    path(
        "simulations/risk-model/",
        RiskModel.as_view(),
        name="simulations-risk-model",
    ),
    path(
        "simulations/vaults-at-risk/",
        VaultsAtRiskSimulationView.as_view(),
        name="simulations-vaults-at-risk",
    ),
    path(
        "simulations/dust/",
        DustSimulationView.as_view(),
        name="simulations-dust",
    ),
    path(
        "risk/liquidation-curve/",
        RiskLiquidationCurveView.as_view(),
        name="liquidation-curve",
    ),
    path(
        "risk/stats/",
        MakerStatsView.as_view(),
        name="maker-stats",
    ),
    path(
        "risk/drop-table/",
        SimulatedLiquidationsPerDropTableView.as_view(),
        name="risk-drop-table",
    ),
    path(
        "risk/gas/",
        GasView.as_view(),
        name="gas-price",
    ),
    path(
        "risk/per-drop/",
        SimulatedLiquidationsPerDropView.as_view(),
        name="risk-drop",
    ),
    path(
        "risk/risky-debt/",
        PercentOfRiskyDebtView.as_view(),
        name="maker-capital-at-risk",
    ),
    path(
        "risk/capital-at-risk/",
        CapitalAtRiskOverallView.as_view(),
        name="maker-capital-at-risk",
    ),
    path(
        "risk/protection-score/history/",
        VaultsProtectionScoreHistoryView.as_view(),
        name="risk-protection-score-history",
    ),
    path(
        "risk/capital-at-risk/ilks/",
        CapitalAtRiskOverallIlkView.as_view(),
        name="maker-capital-at-risk-ilks",
    ),
    path(
        "whales/",
        WhalesView.as_view(),
        name="whales",
    ),
    path(
        "wallets/<str:address>/",
        WalletView.as_view(),
        name="wallet",
    ),
    path(
        "wallets/<str:address>/debt-history/",
        WalletDebtHistoryView.as_view(),
        name="wallet-debt-history",
    ),
    path(
        "wallets/<str:address>/events/",
        WalletEventsView.as_view(),
        name="wallet-events",
    ),
    path(
        "psms/",
        PSMsView.as_view(),
        name="psms",
    ),
    path(
        "psms/dai-supply-history/",
        PSMsDAISupplyHistoryView.as_view(),
        name="psms-dai-supply-history",
    ),
    path(
        "psms/event-stats/",
        PSMsEventStatsView.as_view(),
        name="psms-event-stats",
    ),
    path(
        "psms/<str:ilk>/",
        PSMEventsView.as_view(),
        name="psm",
    ),
    path(
        "psms/<str:ilk>/event-stats/",
        PSMEventStatsView.as_view(),
        name="psm-event-stats",
    ),
    path(
        "psms/<str:ilk>/dai-supply-history/",
        PSMDAISupplyHistoryView.as_view(),
        name="psm-dai-supply-history",
    ),
    path(
        "rates/",
        RatesView.as_view(),
        name="rates",
    ),
    path(
        "defi/eth-market-share/",
        ETHMarketShareView.as_view(),
        name="eth-market-share",
    ),
    path(
        "defi/tvl/<str:symbol>/",
        DEFILockedView.as_view(),
        name="tvl",
    ),
    path(
        "dai-growth/",
        DaiGrowth.as_view(),
        name="dai_growth",
    ),
    path(
        "dai-trades/last-day/",
        DAITradesLastDayView.as_view(),
        name="dai-trades-last-day",
    ),
    path(
        "dai-trades/daily/", DAITradesDailyView.as_view(), name="dai-trades-last-week"
    ),
    path(
        "dai-trades/last-hours/",
        DAITradesLastHoursView.as_view(),
        name="dai-trades-last-hours",
    ),
    path("dai-trades/volume/", DAITradesVolumeView.as_view(), name="dai-trades-volume"),
    path(
        "dai-trades/volume/per-exchange/",
        DAITradesVolumePerExchangeView.as_view(),
        name="dai-trades-volume-per-exchange",
    ),
    path("dai-trades/stats/", DAITradesStatsView.as_view(), name="dai-trades-stats"),
    path("forum-archive/", ForumArchiveView.as_view(), name="forum-archive"),
    path("assets/slippages/", AssetsSlippagesView.as_view(), name="assets-slippages"),
    path(
        "assets/volatility/",
        AssetsVolatilityView.as_view(),
        name="assets-volatility",
    ),
    path("assets/cex/volume/", AssetsCEXVolumeView.as_view(), name="assets-cex-volume"),
    path("assets/dex/volume/", AssetsDEXVolumeView.as_view(), name="assets-dex-volume"),
    path(
        "assets/dex/liquidity/",
        AssetsDEXLiquidityView.as_view(),
        name="assets-dex-liquidity",
    ),
    path(
        "assets/drawdowns/",
        AssetsDrawdownsView.as_view(),
        name="assets-drawdowns",
    ),
    path(
        "assets/collateral/<str:token_address>/",
        AssetCollateralView.as_view(),
        name="assets-collateral",
    ),
    path(
        "assets/debt/<str:token_address>/",
        AssetDebtView.as_view(),
        name="assets-debt",
    ),
    path(
        "assets/<str:symbol>/osm/",
        OSMAsset.as_view(),
        name="osm-asset",
    ),
    path(
        "assets/<str:symbol>/prices/",
        AssetPricesView.as_view(),
        name="osm-asset",
    ),
    path(
        "assets/<str:symbol>/liquidity-score/",
        AssetLiquidityScoreView.as_view(),
        name="asset-liquidity-score",
    ),
    path(
        "assets/<str:symbol>/slippage/",
        AssetSlippageView.as_view(),
        name="asset-slippage",
    ),
    path(
        "assets/<str:symbol>/slippage/history/",
        AssetSlippageHistoryView.as_view(),
        name="asset-slippage-history",
    ),
    path(
        "assets/<str:symbol>/cex/trading-activity/",
        AssetCEXTradingActivityView.as_view(),
        name="asset-cex-trading-activity",
    ),
    path(
        "assets/<str:symbol>/cex/trading-activity/per-exchange/",
        AssetCEXTradingActivityPerExchangeView.as_view(),
        name="asset-cex-trading-activity-per-exchange",
    ),
    path(
        "assets/<str:symbol>/cex/trading-activity/per-asset/",
        AssetCEXTradingActivityPerAssetView.as_view(),
        name="asset-cex-trading-activity-per-asset",
    ),
    path(
        "assets/<str:symbol>/dex/trading-activity/volume/",
        AssetDEXTradingActivityVolumeView.as_view(),
        name="asset-dex-trading-activity-volume",
    ),
    path(
        "assets/<str:symbol>/dex/trading-activity/liquidity/",
        AssetDEXTradingActivityLiquidityView.as_view(),
        name="asset-dex-trading-activity-liquidity",
    ),
    path(
        "assets/<str:symbol>/historical-price/daily-volatility/",
        AssetDailyVolatilityView.as_view(),
        name="asset-historical-price-daily-volatility",
    ),
    path(
        "assets/<str:symbol>/historical-price/drawdowns-price-jumps/",
        AssetPriceDrawdownsView.as_view(),
        name="asset-historical-price-drawdowns-price-jumps/",
    ),
    path(
        "assets/<str:symbol>/OSM/drawdowns/price-jumps/",
        AssetOSMDrawdownsCountView.as_view(),
        name="asset-osm-drawdowns-price-jumps",
    ),
    path("assets/", AssetsView.as_view(), name="assets"),
]
