# SPDX-FileCopyrightText: © 2022 Dai Foundation <www.daifoundation.org>
#
# SPDX-License-Identifier: Apache-2.0

version: "3.10"
volumes:
  ipython_data_local: {}
services:
  web:
    build: .
    env_file:
      - .env
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
      - ipython_data_local:/root/.ipython/profile_default # persist ipython data, including ipython history
    ports:
      - "8000:8000"
    depends_on:
      - db
      - cache
    environment:
      - MAKER_DB_HOST=db
      - MAKER_DB_PASSWORD=postgres
      - MAKER_DB_PORT=5432
      - MAKER_DB_USER=mahcrypto
      - MAKER_CORS_ALLOWED_ORIGINS=http://localhost:3000
      - MAKER_REDIS_HOST=cache
      - MAKER_REDIS_PORT=6379
      - MAKER_DEBUG=1
      - MAKER_CELERY_REDIS_HOST=cache
      - MAKER_CELERY_REDIS_PORT=6379
      - MAKER_INTERNAL_IPS=172.18.0.1;0.0.0.0;localhost;127.0.0.1
      - DJANGO_SETTINGS_MODULE=config.settings.local
    mem_limit: 800M

  db:
    image: postgres:13.4
    volumes:
      - ./.data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=maker
      - POSTGRES_USER=mahcrypto
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

  cache:
    image: redis:6.0
    ports:
      - "6379:6379"
