# SPDX-FileCopyrightText: © 2022 Dai Foundation <www.daifoundation.org>
#
# SPDX-License-Identifier: Apache-2.0

[tool.black]
target-version = ["py310"]
exclude=".*/migrations/.*"
extend-exclude = '''
/(
  # The following are specific to Black, you probably don't want those.
  | .data
)/
'''
skip-numeric-underscore-normalization = true


[tool.isort]
profile = "black"
skip_glob="*/migrations/*"


[tool.pytest.ini_options]
addopts = "--ds=config.settings.test --no-migrations"
