# SPDX-FileCopyrightText: © 2022 Dai Foundation <www.daifoundation.org>
#
# SPDX-License-Identifier: Apache-2.0

# Generated by Django 4.0.7 on 2022-10-05 11:49

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('maker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DEFILocked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('protocol', models.CharField(max_length=64)),
                ('underlying_symbol', models.CharField(max_length=64)),
                ('date', models.DateField()),
                ('datetime', models.DateTimeField()),
                ('timestamp', models.IntegerField()),
                ('balance', models.DecimalField(decimal_places=18, max_digits=32)),
            ],
            options={
                'get_latest_by': 'timestamp',
            },
        ),
    ]
