# SPDX-FileCopyrightText: © 2022 Dai Foundation <www.daifoundation.org>
#
# SPDX-License-Identifier: Apache-2.0

# Generated by Django 4.0.8 on 2022-10-17 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maker', '0002_defilocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='vault',
            name='owner_ens',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
