# Generated by Django 4.0.8 on 2022-10-20 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maker', '0004_vaultowner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MakerWallet',
        ),
        migrations.DeleteModel(
            name='MakerWalletOwner',
        ),
    ]
