# SPDX-FileCopyrightText: © 2022 Dai Foundation <www.daifoundation.org>
#
# SPDX-License-Identifier: Apache-2.0

# Generated by Django 4.0.8 on 2022-10-26 12:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maker', '0006_vaultownergroup_vaultowner_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='ilkhistoricstats',
            name='dc_iam_line',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='vaultowner',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='vaultowner',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='vaultownergroup',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, default=list, size=None),
        ),
    ]
