# SPDX-FileCopyrightText: © 2022 Dai Foundation <www.daifoundation.org>
#
# SPDX-License-Identifier: Apache-2.0

# Generated by Django 4.0.8 on 2022-10-27 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maker", "0007_ilkhistoricstats_dc_iam_line_alter_vaultowner_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vault",
            name="ds_proxy_name",
            field=models.CharField(max_length=64, null=True),
        ),
    ]
