# SPDX-FileCopyrightText: © 2022 Dai Foundation <www.daifoundation.org>
#
# SPDX-License-Identifier: Apache-2.0

# Generated by Django 4.0.8 on 2022-10-27 14:32

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('maker', '0008_vault_ds_proxy_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PSMDAISupply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('ilk', models.CharField(db_index=True, max_length=32)),
                ('datetime', models.DateTimeField(db_index=True)),
                ('timestamp', models.IntegerField()),
                ('total_supply', models.DecimalField(decimal_places=18, max_digits=32)),
                ('supply_change', models.DecimalField(decimal_places=18, max_digits=32)),
            ],
            options={
                'ordering': ['-datetime'],
                'get_latest_by': 'datetime',
                'unique_together': {('ilk', 'datetime')},
            },
        ),
    ]
