# Generated by Django 4.0.8 on 2023-01-21 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maker', '0013_alter_d3m_protocol'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletTokenBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_address', models.CharField(db_index=True, max_length=42)),
                ('amount', models.DecimalField(decimal_places=18, max_digits=32)),
                ('symbol', models.CharField(max_length=16)),
                ('price', models.DecimalField(decimal_places=8, max_digits=32)),
                ('usd_amount', models.DecimalField(decimal_places=8, max_digits=32)),
                ('datetime', models.DateTimeField()),
            ],
            options={
                'get_latest_by': 'datetime',
            },
        ),
    ]
