# Generated by Django 4.0.8 on 2023-01-22 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maker', '0014_wallettokenbalance'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettokenbalance',
            name='chain',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
