# SPDX-FileCopyrightText: © 2022 Dai Foundation <www.daifoundation.org>
#
# SPDX-License-Identifier: Apache-2.0

# Generated by Django 4.0.8 on 2023-01-22 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maker", "0015_wallettokenbalance_chain"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallettokenbalance",
            name="symbol",
            field=models.CharField(max_length=64),
        ),
    ]
