# Generated by Django 4.0.8 on 2023-03-03 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maker', '0016_alter_wallettokenbalance_symbol'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletExternalProtocol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_address', models.CharField(db_index=True, max_length=42)),
                ('protocol', models.CharField(max_length=64)),
                ('protocol_name', models.CharField(max_length=64)),
                ('net_usd_value', models.DecimalField(decimal_places=18, max_digits=32)),
                ('debt_usd_value', models.DecimalField(decimal_places=18, max_digits=32)),
                ('datetime', models.DateTimeField()),
                ('chain', models.CharField(max_length=32, null=True)),
            ],
            options={
                'get_latest_by': 'datetime',
            },
        ),
    ]
