# Generated by Django 4.0.8 on 2023-10-12 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maker', '0018_alter_vault_accrued_fees_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vault',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='vault',
            name='uid',
            field=models.CharField(db_index=True, max_length=42, null=True),
        ),
        migrations.AlterField(
            model_name='vault',
            name='urn',
            field=models.CharField(db_index=True, max_length=42),
        ),
        migrations.AlterUniqueTogether(
            name='vault',
            unique_together={('urn', 'ilk')},
        ),
        migrations.AddIndex(
            model_name='vault',
            index=models.Index(fields=['ilk', 'urn'], name='maker_vault_ilk_6337c3_idx'),
        ),
    ]
