# Generated by Django 4.0.8 on 2023-10-25 12:14

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('maker', '0020_urneventstate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionV1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('ilk', models.CharField(db_index=True, max_length=32)),
                ('symbol', models.CharField(max_length=32, null=True)),
                ('uid', models.IntegerField()),
                ('auction_start', models.DateTimeField(null=True)),
                ('vault', models.CharField(max_length=32, null=True)),
                ('urn', models.CharField(max_length=64, null=True)),
                ('debt', models.DecimalField(decimal_places=18, max_digits=32, null=True)),
                ('debt_liquidated', models.DecimalField(decimal_places=18, max_digits=32, null=True)),
                ('available_collateral', models.DecimalField(decimal_places=18, max_digits=32, null=True)),
                ('kicked_collateral', models.DecimalField(decimal_places=18, max_digits=32, null=True)),
                ('penalty', models.DecimalField(decimal_places=18, max_digits=32, null=True)),
                ('penalty_fee', models.DecimalField(decimal_places=18, max_digits=32, null=True)),
                ('sold_collateral', models.DecimalField(decimal_places=18, max_digits=32, null=True)),
                ('recovered_debt', models.DecimalField(decimal_places=18, max_digits=32, null=True)),
                ('auction_end', models.DateTimeField(null=True)),
                ('finished', models.IntegerField(null=True)),
                ('duration', models.IntegerField(null=True)),
                ('avg_price', models.DecimalField(decimal_places=18, max_digits=32, null=True)),
                ('incentive', models.DecimalField(decimal_places=18, max_digits=32, null=True)),
                ('osm_settled_avg', models.DecimalField(decimal_places=18, max_digits=32, null=True)),
                ('mkt_settled_avg', models.DecimalField(decimal_places=18, max_digits=32, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClipperEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('block_number', models.IntegerField()),
                ('datetime', models.DateTimeField(null=True)),
                ('tx_hash', models.CharField(max_length=66)),
                ('address', models.CharField(max_length=42)),
                ('event', models.CharField(max_length=64)),
                ('ilk', models.CharField(max_length=64)),
                ('auction_id', models.IntegerField()),
                ('top', models.DecimalField(decimal_places=0, max_digits=64, null=True)),
                ('tab', models.DecimalField(decimal_places=0, max_digits=64)),
                ('lot', models.DecimalField(decimal_places=0, max_digits=64)),
                ('usr', models.CharField(max_length=42)),
                ('kpr', models.CharField(max_length=42, null=True)),
                ('coin', models.DecimalField(decimal_places=0, max_digits=64, null=True)),
                ('max', models.DecimalField(decimal_places=0, max_digits=128, null=True)),
                ('price', models.DecimalField(decimal_places=0, max_digits=48, null=True)),
                ('osm_price', models.DecimalField(decimal_places=18, max_digits=32, null=True)),
                ('owe', models.DecimalField(decimal_places=0, max_digits=64, null=True)),
                ('order_index', models.CharField(max_length=26, unique=True)),
                ('penalty', models.DecimalField(decimal_places=0, max_digits=32, null=True)),
            ],
            options={
                'ordering': ['order_index'],
                'get_latest_by': 'order_index',
            },
        ),
        migrations.AddIndex(
            model_name='clipperevent',
            index=models.Index(fields=['order_index'], name='maker_clipp_order_i_23f91c_idx'),
        ),
        migrations.AddIndex(
            model_name='clipperevent',
            index=models.Index(fields=['block_number'], name='maker_clipp_block_n_33fcbd_idx'),
        ),
        migrations.AddIndex(
            model_name='clipperevent',
            index=models.Index(fields=['datetime'], name='maker_clipp_datetim_826dd6_idx'),
        ),
        migrations.AddIndex(
            model_name='clipperevent',
            index=models.Index(fields=['event'], name='maker_clipp_event_501bea_idx'),
        ),
        migrations.AddIndex(
            model_name='clipperevent',
            index=models.Index(fields=['address'], name='maker_clipp_address_54a661_idx'),
        ),
        migrations.AddIndex(
            model_name='clipperevent',
            index=models.Index(fields=['ilk', 'auction_id'], name='maker_clipp_ilk_745d81_idx'),
        ),
    ]
