# Generated by Django 4.0.8 on 2023-10-25 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maker', '0022_clipperevent_osm_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='clipperevent',
            name='penalty',
            field=models.DecimalField(decimal_places=0, max_digits=32, null=True),
        ),
    ]
