# SPDX-FileCopyrightText: © 2022 Dai Foundation <www.daifoundation.org>
#
# SPDX-License-Identifier: Apache-2.0

# Generated by Django 4.0.8 on 2023-11-07 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maker', '0022_auctionevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='slippagedaily',
            name='slippage_percent',
            field=models.DecimalField(decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='slippagedaily',
            name='slippage_percent_max',
            field=models.DecimalField(decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='slippagedaily',
            name='slippage_percent_min',
            field=models.DecimalField(decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='auctionevent',
            name='osm_price',
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
    ]
