# Generated by Django 4.0.8 on 2023-10-25 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maker', '0024_auctionv1'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionv1',
            name='incentive',
            field=models.DecimalField(decimal_places=18, max_digits=32, null=True),
        ),
    ]
