# Generated by Django 4.0.8 on 2023-10-25 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maker', '0025_auctionv1_incentive'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auctionv1',
            old_name='auction_id',
            new_name='uid',
        ),
    ]
