# SPDX-FileCopyrightText: © 2022 Dai Foundation <www.daifoundation.org>
#
# SPDX-License-Identifier: Apache-2.0

name: Test

on:
  pull_request:
    branches:
      - main
      - production

jobs:
  test:
    uses: ./.github/workflows/test.yml
