# SPDX-FileCopyrightText: © 2022 Dai Foundation <www.daifoundation.org>
#
# SPDX-License-Identifier: Apache-2.0

name: Test

on:
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: "3.10.7"
      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ runner.os }}-${{ hashFiles('**/lint-requirements.txt') }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r lint-requirements.txt
      - name: Lint with flake8
        run: flake8 .
      - name: Run black check
        run: black --check .
      - name: Run isort check
        run: isort . --check
      - name: REUSE Compliance Check
        uses: fsfe/reuse-action@v1

  test:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:13.2
        env:
          POSTGRES_DB: maker
          POSTGRES_USER: mahcrypto
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: "3.10.7"
      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ runner.os }}-${{ hashFiles('**/requirements.txt') }}
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run pytest
        run: pytest --ds=config.settings.test tests/
        env:
          MAKER_DB_HOST: localhost
          MAKER_DB_PASSWORD: postgres
          MAKER_DB_USER: mahcrypto
          MAKER_DB_NAME: maker
